name: content-snap-core22
version: '22.04'
summary: Runtime stack based on core22.
description: This snap consists of necessary lib packages that are required by our apps, including ffmpeg, mpv, etc.
grade: stable
confinement: strict
base: core22

architectures:
  - build-on: amd64

slots:
  content-snap-core22:
    interface: content
    read:
      - /

parts:
  platform:
     plugin: nil
     stage-packages:
       - adwaita-icon-theme
       - dmz-cursor-theme
       - gnome-themes-standard
       - gsettings-desktop-schemas
       - libdb5.3
       - libgdk-pixbuf2.0-0
       - libglib2.0-0
       - libglu1-mesa
       - libslang2
       - libxkbcommon0
       - light-themes
       - locales-all
       - qt5-gtk-platformtheme
       - shared-mime-info
       - fonts-ubuntu
       - qt5-image-formats-plugins
       - xdg-user-dirs
       - samba-libs
       - ffmpeg
       - mpv
       - freeglut3
       - libgtk2.0-0

  cleanup:
    after:
      - platform
    plugin: nil
    override-prime: |
      cd usr/share
      rm -rf apport bash-completion bug doc doc-base lintian man pam-configs pkgconfig upstart zsh
